### ISSUE TITLE
US1: account creation/signup

### ISSUE THREAD

**Issue by nicholaskurgan** [nicholaskurgan/Dime-A-Dinner#15]

**Comment by RyanFister** [comment]
AS A grocery shopper, I WANT TO create an account on the "Dime A Dinner" app easily SO THAT I can access my shopping list, pantry, ingredient prices, and recipe recommendations without hassle.

SCENARIO: Successful Account Creation
GIVEN I am on the sign-up page,
WHEN I enter a valid email, password, and confirm password,
THEN I should be redirected to the starting page WITHIN 2 seconds,
AND I should remain logged in for future sessions unless I log out manually.

SCENARIO: Error Message on Mismatched Passwords
GIVEN I am on the sign-up page,
WHEN I enter a password that does not match the confirm password,
THEN I should receive an error message stating "Passwords do not match. Please try again." WITHIN 2 seconds,
AND the sign-up form should remain on the screen for me to re-enter my credentials.

SCENARIO: Error Message on Existing Email
GIVEN I am on the sign-up page,
WHEN I enter an email that is already registered,
THEN I should receive an error message stating "Email already registered. Please log in or use a different email." WITHIN 2 seconds,
AND the sign-up form should remain on the screen for me to re-enter my credentials.

SCENARIO: Password Requirements
GIVEN I am on the sign-up page,
WHEN I enter a password that does not meet the security requirements,
THEN I should receive an error message stating "Password does not meet the security requirements. Please try again." WITHIN 2 seconds,
AND the sign-up form should remain on the screen for me to re-enter my credentials.

Acceptance Criteria:
Account creation should be secure, following industry-standard security protocols.
Users should stay logged in until they log out manually or until 30 days of inactivity.
Error messages should not reveal if the email is already registered for privacy purposes.
